### ISSUE TITLE
Implement getVcfHeaderReferenceSetName

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/ga4gh-server#1171]
Assumes #1166 has been merged.

We should use the pysam VCF header parsing code to attempt a guess at the reference name for a particular Variant set. There are some headers in the VCF spec for this which we should try to use.

**Comment by david4096** [comment]
We do this https://github.com/ga4gh/ga4gh-server/blob/master/ga4gh/server/cli/repomanager.py#L295
