### ISSUE TITLE
Refactor ``getVariantAnnotations`` code path

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/ga4gh-server#1177]
Assumes #1166 has been merged.

Currently the code path that is taken for a given annotation type in the `getVariantAnnotations` method is quite opaque. We should refactor this so that it's clear where the different annotation types share code and where they don't. We should not use the identity of the `transcriptConverter` function for control flow.

**Comment by andrewjesaitis** [comment]
Working on this in conjunction with #1334

**Comment by david4096** [comment]
Closing based on https://github.com/ga4gh/ga4gh-server/pull/1562
