### ISSUE TITLE
RNA data needs to be managed by repomanager

### ISSUE THREAD

**Issue by saupchurch** [ga4gh/ga4gh-server#1227]
Update RNA topic branch to:
- remove references to prior data directory structure
- add functions to manage RNA data to `cli.py` and probably also `datarepo.py`

**Comment by saupchurch** [comment]
fixed in #1231

**Comment by david4096** [comment]
This is done here: https://github.com/ga4gh/ga4gh-server/blob/master/ga4gh/server/cli/repomanager.py#L564
