### ISSUE TITLE
Replace call to `run_tests` in documentation

### ISSUE THREAD

**Issue by achave11** [ga4gh/ga4gh-server#1463]
In `http://ga4gh-reference-implementation.readthedocs.io/en/latest/installation.html#installing-the-development-version-on-mac-os-x`
Under `Test and run` when I ran the script for testing it wouldn't ran, and complained `IOError: [Errno 2] No such file or directory: u'.travis.yml'`

**Comment by david4096** [comment]
That should probably just say `python -m nose tests` to run tests instead. That script isn't in the source tree, is it?

**Comment by dcolligan** [comment]
The `ga4gh_common` package should install a executable called `ga4gh_run_tests` which replaces the `scripts/run_tests.py` scripts

**Comment by david4096** [comment]
Closed with https://github.com/ga4gh/ga4gh-server/commit/77d42db46268875549511edfffab2dca22528c5e
