### ISSUE TITLE
Update package name to ga4gh-server

### ISSUE THREAD

**Issue by david4096** [ga4gh/ga4gh-server#1469]
When installing via pip we can use `ga4gh-server` to make the separation of concerns more clear.

**Comment by dcolligan** [comment]
We would probably need to deprecate / remove the `ga4gh` pypi package to do this.  Are we ok with doing that?

**Comment by david4096** [comment]
Yes, this makes sense to me. I seem to recall a way of telling pypi about deprecating a module but can't seem to find it now.

**Comment by david4096** [comment]
@kozbo The next release would be a good time to do this. http://stackoverflow.com/questions/24085400/how-to-formally-deprecate-a-pip-package

**Comment by david4096** [comment]
Bumping this... this is quickly going to get annoying if we don't do it soon.

**Comment by david4096** [comment]
Closing in favor of https://github.com/ga4gh/ga4gh-server/issues/1583
https://github.com/ga4gh/ga4gh-server/pull/1582
