### ISSUE TITLE
Rename server pypi package

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/ga4gh-server#1583]
ga4gh -> ga4gh-server

**Comment by dcolligan** [comment]
Code merged in #1582 ...

Still need to:
- upload a new package to pypi's ga4gh-server
- deprecate ga4gh package

**Comment by david4096** [comment]
Please close this after we've tested the release process @dcolligan @kozbo

**Comment by dcolligan** [comment]
Done

https://pypi.python.org/pypi/ga4gh-server
