### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/ga4gh-server#1585]
To maintain consistency with other ga4gh repositories, perhaps we should rename this one to `ga4gh-server`?

https://help.github.com/articles/renaming-a-repository/

We also would need to:
- change the documentation to point to the new URL
- perhaps change the auto deploy key

**Comment by david4096** [comment]
+1 and the same at schemas.

**Comment by david4096** [comment]
I'd also like to rename the RTD address to be the same `ga4gh-server`.

**Comment by dcolligan** [comment]
@david4096 I filed a new issue for that: https://github.com/ga4gh/server/issues/1591

**Comment by david4096** [comment]
Just did this to my repository and observed this message:

```
(env) ➜  schemas git:(master) ✗ git push origin master
Total 0 (delta 0), reused 0 (delta 0)
remote: This repository moved. Please use the new location:
remote:   git@github.com:david4096/ga4gh-schemas.git
To github.com:david4096/schemas.git
   12381a6..5458bc8  master -> master
```

Which I silenced using `git remote set-url origin git@github.com:david4096/ga4gh-schemas.git`.

**Comment by david4096** [comment]
https://github.com/ga4gh/ga4gh-server/issues/1585
