### ISSUE TITLE
Server does not always return next page token

### ISSUE THREAD

**Issue by Welliton309** [ga4gh/ga4gh-server#1635]
I noticed that the 1kgenomes server (http://1kgenomes.ga4gh.org/) does not return `nextPageToken` attribute when response data size is less or equal `pageSize`. It only returns this attribute when there is some value for `nextPageToken`. It was not the default behavior previously, which the same server always returned `nextPageToken = ""` by default. Is this the default behavior now?

**Comment by david4096** [comment]
Yes, we changed the protobuf serialization to not include empty keys.

Did this break your client? It's probably safer in your client to check for the presence of a key before checking it's value!

**Comment by Welliton309** [comment]
Thank you @david4096. I will update my software client. I checked the presence of keys that are optional. I thought that `nextPageToken` would always present. Knowing that any empty key will be omitted I will take more attention.
