### ISSUE TITLE
API extension - Elastic Net Coefficients predicting Drug Response (hackathon idea)

### ISSUE THREAD

**Issue by bwalsh** [ga4gh/ga4gh-server#663]
While the bulk of recent work has focused on schema implementation.  It would be useful to have an end-to-end workflow to illustrate net new activities.  This example would show:
- requirements
- schema creation
- reference implementation
- unit tests 
- compliance tests.

One idea that should be small enough to implement, yet useful in its own right is to create an endpoint to capture the results of a machine learning model.

```
Briefly, capture the outputted coefficients of an elastic net model on a matrix of samples by features in such a way that the trained model can be run on a novel samples by features dataset.  

The system should store and retrieve the matrix and coefficients in a ga4gh compliant way and allow the user to query by features, response and model.
```

[2015-08-29_DrugResponseSubset.txt](https://github.com/ga4gh/server/files/5617/2015-08-29_DrugResponseSubset.txt)

[2015-09-29_CoefficientsSubset.txt](https://github.com/ga4gh/server/files/5616/2015-09-29_CoefficientsSubset.txt)

**Comment by david4096** [comment]
@bwalsh what do you think? Can we close this one? This is related to ongoing efforts to associate evidence claims with associations perhaps.
