### ISSUE TITLE
Add header information to ga2sam

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/ga4gh-server#706]
(This issue is part of a trio of closely related issues #705, #706 and #707 that would be well suited to a group of people working together on.)

The `ga2sam` utility converts the results of a `reads/search` request to the server into SAM/BAM format using pysam. This utility is roughtly functional, but needs some work to fill out the rough corners. One area that hasn't been worked on is writing an appropriate header.

To try this out ga2sam, run (assuming you are running a server with the example data)

```
$ python ga2sam_dev.py http://localhost:8000 MWtnLXAzLXN1YnNldDpIRzAwMDk2OlNSUjA2MjYzNQ== --referenceId=R1JDaDM4LXN1YnNldDoz | less -S
```

The header is just some fabricated data, and we want to fix this.

Edit `ga4gh/converters.py` and find the `_getHeader` function. We need to generate a header that conforms to what [pysam expects](http://pysam.readthedocs.org/en/latest/usage.html#) and compatible with the [SAM spec](https://samtools.github.io/hts-specs/SAMv1.pdf).

We want to add reference headers at a minimum. Use the information in `self._reference` (see the [client API docs](http://ga4gh-reference-implementation.readthedocs.org/en/develop/api.html#references) for details) to add some SQ headers.

**Comment by david4096** [comment]
Related https://github.com/ga4gh/ga4gh-server/issues/1457

**Comment by david4096** [comment]
Closing, future converter development can be seen here https://github.com/BD2KGenomics/ga4gh-integration/issues/67
