### ISSUE TITLE
Update ga2sam tests to check all fields

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/ga4gh-server#707]
(This issue is part of a trio of closely related issues #705, #706 and #707 that would be well suited to a group of people working together on.)

The ga2sam utility is tested by converting a specific readGroupSet to SAM format and comparing with the original BAM file. This is done in `tests/unit/test_converters.py`. Run the tests by running `nosetests -vs tests/unit/test_converters.py`.

Update the verifySamRecordsEqual function to compare the full record (currently the check is very incomplete). Ideally, we'd like to convert both records to SAM text format and compare these. The conversion code is quite raw, so there may well be bugs in there.

If #705 has been resolved, update the testSamConversion method to check all readGroups and references on the server. (These fill fail currently because of the bug in #705.)

If #706 has been resolved, add tests for the headers to check that these have been converted correctly.

**Comment by david4096** [comment]
Closing, for continued development see https://github.com/BD2KGenomics/ga4gh-integration/issues/67
