### ISSUE TITLE
404 status code returned incorrectly

### ISSUE THREAD

**Issue by david4096** [ga4gh/ga4gh-server#883]
When using search endpoints a `404` status code is returned if the datasetId is not present. This breaks common conventions, `404` is meant when a resource does not exist. Common search idioms return empty lists when the search terms are not matched on.

**Comment by diekhans** [comment]
@david4096 this should be a ticket in schemas, as they need to define
exactly what the expected behavior is.

**Comment by jeromekelleher** [comment]
This is the documented behavior @david4096, and has been discussed a few times. This is a good example: https://github.com/ga4gh/schemas/issues/382

I think Mark's SQL analogy is a good one. 

Closing this issue as it is the documented behavior.

**Comment by david4096** [comment]
Related https://github.com/ga4gh/schemas/issues/382
